---
- name: Ensure ssh dir exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user_group }}"
    mode: "0700"

- name: Ensure ssh keys copied
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ssh_dir }}/{{ item | basename }}"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: "0600"
  loop:
    - "{{ ssh_private_key }}"
    - "{{ ssh_public_key }}"
