---
- name: Runs preflight tasks
  include_tasks: preflight.yml

- name: Ensure ssh key dirs exists
  file:
    path: "{{ ssh_key_dir }}"
    owner: "{{ ssh_key_user }}"
    group: "{{ ssh_key_group }}"
    mode: "0700"
    state: directory

- name: Configures path
  set_fact:
    ssh_private: "{{ ssh_key_dir }}/{{ ssh_key_filename }}"
    ssh_private_backup: "{{ ssh_backup_dir }}/{{ ssh_key_filename }}"
    ssh_public: "{{ ssh_key_dir }}/{{ ssh_key_filename }}.pub"
    ssh_public_backup: "{{ ssh_backup_dir }}/{{ ssh_key_filename }}.pub"

- name: Check existing backup keys
  local_action:
    module: stat
    path: "{{ ssh_private_backup }}"
  register: rs_ssh_backup

- name: Check existing keys
  stat:
    path: "{{ ssh_private }}"
  register: rs_ssh_existing

- name: Restore existing key
  include_tasks: restore.yml
  when: rs_ssh_backup.stat.exists

- name: Generate new key
  include_tasks: generate.yml
  when: not rs_ssh_backup.stat.exists and not rs_ssh_existing.stat.exists

- name: Backup existing key
  include_tasks: backup.yml

- name: Upload keys to github
  include_tasks: github.yml
  when: github_token != ""
