---
- name: "{{ ssh_key_filename }} ~> restore private key"
  copy:
    src: "{{ ssh_private_backup }}"
    dest: "{{ ssh_private }}"
    owner: "{{ ssh_key_user }}"
    group: "{{ ssh_key_group }}"
    mode: "0600"

- name: "{{ ssh_key_filename }} ~> restore public key"
  copy:
    src: "{{ ssh_public_backup }}"
    dest: "{{ ssh_public }}"
    owner: "{{ ssh_key_user }}"
    group: "{{ ssh_key_group }}"
