---
- name: Converge
  hosts: all
  vars:
    ssh_user: "testing"
  pre_tasks:
    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ ssh_user_group }}"
        state: "present"
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        group: "{{ ssh_user_group }}"
        state: present
  roles:
    - role: "kilip.ssh"
