---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ssh
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

lint: |
  set -e
  ansible-lint

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
