---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  push:
    branches: ["main", "1.x"]


jobs:
  testing:
    uses: kilip/gh-common/.github/workflows/ansible-testing.yml@main
    with:
      dists: ubuntu-22.04,debian-12
